name: Siemens SOMATOM go.Sim Daily QA
category: CT
protocol: CT Daily QA

machine:
  vendor: Siemens
  model: SOMATOM go.Sim

frequency: daily

guideline:
  - AAPM TG-66
  - Sentinel Service Manual

phantom:
  name: Catphan 503

sections:

  - key: ct_daily
    name: CT Daily QA

    tests:

      - key: ct_daily_laser_gantry_moving
        name: Gantry / Moving Laser Alignment
        description:
        type: boolean
        unit: mm
        tolerance: 1
        tolerance_source: AAPM TG-66
        trend: false

      - key: ct_daily_laser_moving_scan_plane
        name: Moving Laser / Scan Plane Alignment
        description:
        type: boolean
        unit: mm
        tolerance: 1
        tolerance_source: AAPM TG-66
        trend: false

      - key: ct_daily_spatial_integrity
        name: Spatial Integrity (distance)
        description: Distance between phantom markers
        type: numeric
        unit: mm
        reference: 199.0
        reference_source: Acceptance test
        tolerance: 2
        tolerance_source: AAPM TG-66
        trend: true

      - key: ct_daily_hu_water
        name: CT Number Accuracy of Water
        description: CT Number Accuracy of Water
        type: numeric
        unit: HU
        reference: 0
        reference_source: Acceptance test
        tolerance: 5
        tolerance_source: AAPM TG-66
        trend: true

      - key: ct_daily_hu_air
        name: CT Number Accuracy of Air
        description: CT Number Accuracy of Air
        type: numeric
        unit: HU
        reference: -1000
        reference_source: Acceptance test
        tolerance: 5
        tolerance_source: AAPM TG-66
        trend: true

      - key: ct_daily_sd_water
        name: Image Noise of Water
        description: Image Noise(Standard Deviation) of Water
        type: numeric
        unit: HU
        reference: 4
        reference_source: Acceptance test
        tolerance: 1
        tolerance_source: AAPM TG-66
        trend: true

      - key: ct_daily_sd_air
        name: Image Noise of Air
        description: Image Noise(Standard Deviation) of Air
        type: numeric
        unit: HU
        reference: 2
        reference_source: Acceptance test
        tolerance: 1
        tolerance_source: AAPM TG-66
        trend: true

  - key: sentinel_daily
    name: Sentinel Daily QA

    tests:

      - key: sentinel_daily_isochk
        name: Sentinel Isocenter Check
        description: Sentinel phantom Isosenter Check
        type: boolean
        trend: false

      - key: sentinel_couch_profile
        name: Couch Profile Deviation
        description:
        type: numeric
        unit: mm
        reference: 0
        reference_source: Sentinel
        tolerance: 2
        tolerance_source: Sentinel
        trend: true