name: Siemens SOMATOM go.Sim
category: CT
protocol: CT Daily QA

sections:

  - key: ct_daily
    name: CT Daily QA

    tests:

      - key: gantry_moving_laser_alignment
        name: Gantry / Moving Laser Alignment
        type: boolean
        trend: false

      - key: moving_laser_scan_plane_alignment
        name: Moving Laser / Scan Plane Alignment
        type: boolean
        trend: false

      - key: spatial_integrity
        name: Spatial Integrity (distance)
        type: numeric
        unit: mm
        tolerance: 1
        reference: 200
        baseline: 199.3
        trend: true

      - key: hu_water
        name: CT Number Accuracy of Water
        type: numeric
        unit: HU
        tolerance: 5
        reference: 0
        baseline: 0
        trend: true

      - key: hu_air
        name: CT Number Accuracy of Air
        type: numeric
        unit: HU
        tolerance: 5
        reference: -1000
        baseline: -1000
        trend: true

      - key: noise_water
        name: Image Noise of Water
        type: numeric
        unit: HU
        tolerance: 1
        reference: 4
        baseline: 4
        trend: true

      - key: noise_air
        name: Image Noise of Air
        type: numeric
        unit: HU
        tolerance: 1
        reference: 2
        baseline: 2
        trend: true

  - key: sentinel_daily
    name: Sentinel Daily QA

    tests:

      - key: sentinel_isocenter_check
        name: Sentinel Isocenter Check
        type: boolean
        trend: false

      - key: couch_profile_deviation
        name: Couch Profile Deviation
        type: numeric
        unit: mm
        tolerance: 3
        reference: 0
        baseline: 0
        trend: true